"""Closed vocabularies for the pure execution domain."""

from ..models import StrEnum


class ExecutionState(StrEnum):
    DISABLED = "DISABLED"
    RECONCILING = "RECONCILING"
    NORMAL = "NORMAL"
    PRECHECK = "PRECHECK"
    TRANSITION = "TRANSITION"
    SOLAX_HOLD = "SOLAX_HOLD"
    SOLAX_DISPATCH = "SOLAX_DISPATCH"
    DEYE_START_REQUIRED = "DEYE_START_REQUIRED"
    DEYE_STARTING = "DEYE_STARTING"
    DEYE_HOLD = "DEYE_HOLD"
    DEYE_DISPATCH = "DEYE_DISPATCH"
    ROLLBACK = "ROLLBACK"
    SAFE_STOP = "SAFE_STOP"


class PhysicalRole(StrEnum):
    NATIVE = "NATIVE"
    OFF = "OFF"
    HOLD = "HOLD"
    CHARGE = "CHARGE"
    DISCHARGE = "DISCHARGE"


class PlannerIntentType(StrEnum):
    NORMAL = "NORMAL"
    CHARGE_SOLAX = "CHARGE_SOLAX"
    DISCHARGE_SOLAX = "DISCHARGE_SOLAX"
    CHARGE_DEYE = "CHARGE_DEYE"
    DISCHARGE_DEYE = "DISCHARGE_DEYE"


class ExecutorDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    DEFERRED = "DEFERRED"
    CLAMPED = "CLAMPED"
    REJECTED = "REJECTED"
    ABORTED = "ABORTED"
    FAILED = "FAILED"


class CommandLifecycleState(StrEnum):
    INTENT_CREATED = "INTENT_CREATED"
    COMMAND_ISSUED = "COMMAND_ISSUED"
    READBACK_CONFIRMED = "READBACK_CONFIRMED"
    PHYSICAL_RESPONSE_CONFIRMED = "PHYSICAL_RESPONSE_CONFIRMED"
    STABLE = "STABLE"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class TransitionPhase(StrEnum):
    FREEZE_INTENT = "FREEZE_INTENT"
    STOP_CURRENT_OWNER = "STOP_CURRENT_OWNER"
    WAIT_CURRENT_ACK = "WAIT_CURRENT_ACK"
    WAIT_NEUTRAL = "WAIT_NEUTRAL"
    VERIFY_PCC = "VERIFY_PCC"
    ARM_DESTINATION = "ARM_DESTINATION"
    WAIT_DESTINATION_READY = "WAIT_DESTINATION_READY"
    ISSUE_TARGET = "ISSUE_TARGET"
    WAIT_TARGET_ACK = "WAIT_TARGET_ACK"
    WAIT_PHYSICAL_RESPONSE = "WAIT_PHYSICAL_RESPONSE"
    WAIT_STABLE = "WAIT_STABLE"
    COMPLETE = "COMPLETE"


class FailureReason(StrEnum):
    DISABLED = "DISABLED"
    STALE_TELEMETRY = "STALE_TELEMETRY"
    MISSING_TELEMETRY = "MISSING_TELEMETRY"
    TELEMETRY_INCOHERENT = "TELEMETRY_INCOHERENT"
    PCC_STALE = "PCC_STALE"
    PCC_IMPLAUSIBLE = "PCC_IMPLAUSIBLE"
    PCC_EXPORT_LIMIT = "PCC_EXPORT_LIMIT"
    PCC_ROLLING_LIMIT = "PCC_ROLLING_LIMIT"
    CROSS_BATTERY_FLOW = "CROSS_BATTERY_FLOW"
    WRITER_CONFLICT = "WRITER_CONFLICT"
    INVERTER_UNAVAILABLE = "INVERTER_UNAVAILABLE"
    DEYE_NOT_READY = "DEYE_NOT_READY"
    DEYE_START_TIMEOUT = "DEYE_START_TIMEOUT"
    MODE_UNVERIFIED = "MODE_UNVERIFIED"
    UNSUPPORTED_INTENT = "UNSUPPORTED_INTENT"
    AMBIGUOUS_PLANNER_SLOT = "AMBIGUOUS_PLANNER_SLOT"
    READBACK_MISMATCH = "READBACK_MISMATCH"
    READBACK_EVIDENCE_MISSING = "READBACK_EVIDENCE_MISSING"
    COMMAND_TIMEOUT = "COMMAND_TIMEOUT"
    PHYSICAL_RESPONSE_TIMEOUT = "PHYSICAL_RESPONSE_TIMEOUT"
    COMMAND_EXPIRED = "COMMAND_EXPIRED"
    DUPLICATE_COMMAND_ID = "DUPLICATE_COMMAND_ID"
    OLD_EXECUTION_EPOCH = "OLD_EXECUTION_EPOCH"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    INVALID_INTENT = "INVALID_INTENT"
    TRANSITION_FORBIDDEN = "TRANSITION_FORBIDDEN"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    RESTART_RECONCILIATION = "RESTART_RECONCILIATION"
    COMMAND_ID_MISMATCH = "COMMAND_ID_MISMATCH"
    OBSERVATION_OUT_OF_ORDER = "OBSERVATION_OUT_OF_ORDER"
    PHYSICAL_RESPONSE_MISMATCH = "PHYSICAL_RESPONSE_MISMATCH"
    STABILITY_NOT_CONFIRMED = "STABILITY_NOT_CONFIRMED"


class SafetyAction(StrEnum):
    NONE = "NONE"
    CLAMP = "CLAMP"
    DEFER = "DEFER"
    ROLLBACK = "ROLLBACK"
    SAFE_STOP = "SAFE_STOP"
