from __future__ import annotations

from typing import Any

from .charge_controller import ChargeControllerParameters, validate_charge_controller_parameters

ENTITY_IDS: dict[str, str] = {
    "solax_soc": "sensor.solax_battery_capacity",
    "solax_battery_power": "sensor.solax_battery_power_charge",
    "solax_pv_power": "sensor.solax_pv_power_total",
    "solax_house_load": "sensor.solax_house_load",
    "solax_inverter_power": "sensor.solax_inverter_power",
    "solax_measured_power": "sensor.solax_measured_power",
    "solax_measured_power_l1": "sensor.solax_measured_power_l1",
    "solax_measured_power_l2": "sensor.solax_measured_power_l2",
    "solax_measured_power_l3": "sensor.solax_measured_power_l3",
    "solax_grid_import": "sensor.solax_grid_import",
    "solax_grid_export": "sensor.solax_grid_export",
    "deye_soc": "sensor.deye_battery",
    "deye_inverter_power": "sensor.deye_power",
    "deye_battery_power": "sensor.battery_power_otoceny",
    "deye_battery_power_raw": "sensor.deye_battery_power",
    "deye_battery_voltage": "sensor.deye_battery_voltage",
    "deye_battery_state": "sensor.deye_battery_state",
    "deye_grid_power": "sensor.deye_grid_power",
    "deye_external_power": "sensor.deye_external_power",
    "deye_device_state": "sensor.deye_device_state",
    "deye_connection": "binary_sensor.deye_connection",
    "buy_price": "sensor.current_buy_electricity_price_15min",
    "sell_price": "sensor.current_sell_electricity_price_15min",
    "future_sell_rank": "sensor.energy_trading_budouci_poradi_prodejni_ceny",
    "deye_grid_charging": "switch.deye_battery_grid_charging",
    "deye_export_surplus": "switch.deye_export_surplus",
    "deye_charge_current": "number.deye_battery_max_charging_current",
    "solax_charger_use_mode": "select.solax_charger_use_mode",
    "deye_ac_coupling": "select.deye_ac_coupling",
    "deye_time_of_use": "select.deye_time_of_use",
    "deye_work_mode": "select.deye_work_mode",
    "legacy_enabled": "input_boolean.energy_trading_puvodni_reseni_povoleno",
    "current_energy_trading_enabled": "input_boolean.energy_trading_novy_system_povolen",
    "energy_v2_enabled": "input_boolean.energy_v2_enabled",
    "energy_v2_shadow_mode": "input_boolean.energy_v2_shadow_mode",
    "energy_v2_export_enabled": "input_boolean.energy_v2_export_enabled",
    "energy_v2_service_mode": "input_boolean.energy_v2_service_mode",
    "energy_v2_safe_to_enable": "input_boolean.energy_v2_safe_to_enable",
    "energy_v2_strategy": "input_select.energy_v2_strategy",
    "energy_v2_requested_mode": "input_select.energy_v2_requested_mode",
    "energy_v2_actual_mode": "input_select.energy_v2_actual_mode",
    "energy_v2_flow_state": "input_select.energy_v2_flow_state",
    "energy_v2_flow_summary": "input_text.energy_v2_flow_summary",
    "energy_v2_flow_warning": "input_text.energy_v2_flow_warning",
    "energy_v2_flow_violation": "input_text.energy_v2_flow_violation",
    "energy_v2_last_flow_violation": "input_datetime.energy_v2_last_flow_violation",
    "energy_v2_instant_grid_export_w": "input_number.energy_v2_instant_grid_export_w",
    "energy_v2_rolling_15min_export_w": "input_number.energy_v2_rolling_15min_export_w",
    "energy_v2_export_window_covered_s": "input_number.energy_v2_export_window_covered_s",
    "energy_v2_export_sample_age_s": "input_number.energy_v2_export_sample_age_s",
    "energy_v2_export_limit_state": "input_select.energy_v2_export_limit_state",
    "energy_v2_export_limit_summary": "input_text.energy_v2_export_limit_summary",
    "energy_v2_last_valid_export_sample": "input_datetime.energy_v2_last_valid_export_sample",
    "energy_v2_last_export_average_violation": "input_datetime.energy_v2_last_export_average_violation",
    "energy_v2_last_fault": "input_text.energy_v2_last_fault",
    "energy_v2_last_decision": "input_text.energy_v2_last_decision",
    "energy_v2_active_conflicts": "input_text.energy_v2_active_conflicts",
    "energy_v2_heartbeat": "input_datetime.energy_v2_heartbeat",
    "energy_v2_last_successful_evaluation": "input_datetime.energy_v2_last_successful_evaluation",
    "energy_v2_last_evaluation_error": "input_text.energy_v2_last_evaluation_error",
    "energy_v2_app_status": "input_select.energy_v2_app_status",
    "energy_v2_deye_fv_ledger": "input_number.energy_v2_deye_fv_ledger",
    "energy_v2_solax_fv_ledger": "input_number.energy_v2_solax_fv_ledger",
    "energy_v2_charge_shadow_enabled": "input_boolean.energy_v2_charge_shadow_enabled",
    "energy_v2_charge_shadow_state": "input_select.energy_v2_charge_shadow_state",
    "energy_v2_charge_recommended_state": "input_select.energy_v2_charge_recommended_state",
    "energy_v2_recommended_deye_charge_current_a": "input_number.energy_v2_recommended_deye_charge_current_a",
    "energy_v2_charge_start_confirmation_s": "input_number.energy_v2_charge_start_confirmation_s",
    "energy_v2_charge_transfer_confirmation_s": "input_number.energy_v2_charge_transfer_confirmation_s",
    "energy_v2_charge_return_confirmation_s": "input_number.energy_v2_charge_return_confirmation_s",
    "energy_v2_charge_fault_recovery_s": "input_number.energy_v2_charge_fault_recovery_s",
    "energy_v2_solax_discharge_average_w": "input_number.energy_v2_solax_discharge_average_w",
    "energy_v2_deye_charge_average_w": "input_number.energy_v2_deye_charge_average_w",
    "energy_v2_deye_voltage_average_v": "input_number.energy_v2_deye_voltage_average_v",
    "energy_v2_calculated_safe_charge_power_w": "input_number.energy_v2_calculated_safe_charge_power_w",
    "energy_v2_calculated_safe_current_a": "input_number.energy_v2_calculated_safe_current_a",
    "energy_v2_charge_conflict_count": "input_number.energy_v2_charge_conflict_count",
    "energy_v2_charge_conflict_state": "input_select.energy_v2_charge_conflict_state",
    "energy_v2_charge_decision_reason": "input_text.energy_v2_charge_decision_reason",
    "energy_v2_charge_block_reason": "input_text.energy_v2_charge_block_reason",
    "energy_v2_charge_mode_mismatches": "input_text.energy_v2_charge_mode_mismatches",
    "energy_v2_charge_shadow_summary": "input_text.energy_v2_charge_shadow_summary",
    "energy_v2_charge_conflict_summary": "input_text.energy_v2_charge_conflict_summary",
    "energy_v2_control_shadow_enabled": "input_boolean.energy_v2_control_shadow_enabled",
    "energy_v2_whole_site_load_w": "input_number.energy_v2_whole_site_load_w",
    "energy_v2_load_quality": "input_select.energy_v2_load_quality",
    "energy_v2_load_summary": "input_text.energy_v2_load_summary",
    "energy_v2_requested_site_target_w": "input_number.energy_v2_requested_site_target_w",
    "energy_v2_budget_diagnostic_target_w": "input_number.energy_v2_budget_diagnostic_target_w",
    "energy_v2_deye_requested_power_w": "input_number.energy_v2_deye_requested_power_w",
    "energy_v2_deye_allowed_power_w": "input_number.energy_v2_deye_allowed_power_w",
    "energy_v2_deye_predicted_power_w": "input_number.energy_v2_deye_predicted_power_w",
    "energy_v2_deye_actual_power_w": "input_number.energy_v2_deye_actual_power_w",
    "energy_v2_solax_requested_power_w": "input_number.energy_v2_solax_requested_power_w",
    "energy_v2_solax_predicted_power_w": "input_number.energy_v2_solax_predicted_power_w",
    "energy_v2_solax_actual_power_w": "input_number.energy_v2_solax_actual_power_w",
    "energy_v2_whole_site_grid_actual_w": "input_number.energy_v2_whole_site_grid_actual_w",
    "energy_v2_grid_error_w": "input_number.energy_v2_grid_error_w",
    "energy_v2_anti_transfer_state": "input_select.energy_v2_anti_transfer_state",
    "energy_v2_break_before_make_state": "input_text.energy_v2_break_before_make_state",
    "energy_v2_command_status": "input_select.energy_v2_command_status",
    "energy_v2_command_expiry": "input_datetime.energy_v2_command_expiry",
    "energy_v2_saturation_reason": "input_text.energy_v2_saturation_reason",
    "energy_v2_fixed_used_export_kwh": "input_number.energy_v2_fixed_used_export_kwh",
    "energy_v2_fixed_remaining_operational_kwh": "input_number.energy_v2_fixed_remaining_operational_kwh",
    "energy_v2_fixed_remaining_legal_kwh": "input_number.energy_v2_fixed_remaining_legal_kwh",
    "energy_v2_fixed_seconds_remaining": "input_number.energy_v2_fixed_seconds_remaining",
    "energy_v2_fixed_budget_power_w": "input_number.energy_v2_fixed_budget_power_w",
    "energy_v2_fixed_projected_average_w": "input_number.energy_v2_fixed_projected_average_w",
    "energy_v2_trailing_remaining_operational_kwh": "input_number.energy_v2_trailing_remaining_operational_kwh",
    "energy_v2_trailing_remaining_legal_kwh": "input_number.energy_v2_trailing_remaining_legal_kwh",
    "energy_v2_trailing_budget_power_w": "input_number.energy_v2_trailing_budget_power_w",
    "energy_v2_trailing_projected_average_w": "input_number.energy_v2_trailing_projected_average_w",
}

REQUIRED_TELEMETRY_KEYS: tuple[str, ...] = (
    "solax_soc",
    "solax_battery_power",
    "solax_pv_power",
    "solax_inverter_power",
    "solax_measured_power",
    "solax_grid_import",
    "solax_grid_export",
    "deye_soc",
    "deye_inverter_power",
    "deye_battery_power",
    "deye_battery_state",
    "deye_grid_power",
    "deye_external_power",
    "deye_device_state",
    "deye_connection",
    "buy_price",
    "sell_price",
    "deye_grid_charging",
    "deye_export_surplus",
)

OPTIONAL_TELEMETRY_KEYS: tuple[str, ...] = (
    "solax_house_load",
    "future_sell_rank",
    "solax_measured_power_l1",
    "solax_measured_power_l2",
    "solax_measured_power_l3",
    "deye_battery_power_raw",
    "deye_battery_voltage",
)

ENERGY_V2_HELPER_KEYS: tuple[str, ...] = (
    "energy_v2_enabled",
    "energy_v2_shadow_mode",
    "energy_v2_export_enabled",
    "energy_v2_service_mode",
    "energy_v2_safe_to_enable",
    "energy_v2_strategy",
    "energy_v2_requested_mode",
    "energy_v2_actual_mode",
    "energy_v2_flow_state",
    "energy_v2_flow_summary",
    "energy_v2_flow_warning",
    "energy_v2_flow_violation",
    "energy_v2_last_flow_violation",
    "energy_v2_instant_grid_export_w",
    "energy_v2_rolling_15min_export_w",
    "energy_v2_export_window_covered_s",
    "energy_v2_export_sample_age_s",
    "energy_v2_export_limit_state",
    "energy_v2_export_limit_summary",
    "energy_v2_last_valid_export_sample",
    "energy_v2_last_export_average_violation",
    "energy_v2_last_fault",
    "energy_v2_last_decision",
    "energy_v2_active_conflicts",
    "energy_v2_heartbeat",
    "energy_v2_last_successful_evaluation",
    "energy_v2_last_evaluation_error",
    "energy_v2_app_status",
    "energy_v2_deye_fv_ledger",
    "energy_v2_solax_fv_ledger",
    "energy_v2_charge_shadow_enabled",
    "energy_v2_charge_shadow_state",
    "energy_v2_charge_recommended_state",
    "energy_v2_recommended_deye_charge_current_a",
    "energy_v2_charge_start_confirmation_s",
    "energy_v2_charge_transfer_confirmation_s",
    "energy_v2_charge_return_confirmation_s",
    "energy_v2_charge_fault_recovery_s",
    "energy_v2_solax_discharge_average_w",
    "energy_v2_deye_charge_average_w",
    "energy_v2_deye_voltage_average_v",
    "energy_v2_calculated_safe_charge_power_w",
    "energy_v2_calculated_safe_current_a",
    "energy_v2_charge_conflict_count",
    "energy_v2_charge_conflict_state",
    "energy_v2_charge_decision_reason",
    "energy_v2_charge_block_reason",
    "energy_v2_charge_mode_mismatches",
    "energy_v2_charge_shadow_summary",
    "energy_v2_charge_conflict_summary",
    "energy_v2_control_shadow_enabled",
    "energy_v2_whole_site_load_w",
    "energy_v2_load_quality",
    "energy_v2_load_summary",
    "energy_v2_requested_site_target_w",
    "energy_v2_budget_diagnostic_target_w",
    "energy_v2_deye_requested_power_w",
    "energy_v2_deye_allowed_power_w",
    "energy_v2_deye_predicted_power_w",
    "energy_v2_deye_actual_power_w",
    "energy_v2_solax_requested_power_w",
    "energy_v2_solax_predicted_power_w",
    "energy_v2_solax_actual_power_w",
    "energy_v2_whole_site_grid_actual_w",
    "energy_v2_grid_error_w",
    "energy_v2_anti_transfer_state",
    "energy_v2_break_before_make_state",
    "energy_v2_command_status",
    "energy_v2_command_expiry",
    "energy_v2_saturation_reason",
    "energy_v2_fixed_used_export_kwh",
    "energy_v2_fixed_remaining_operational_kwh",
    "energy_v2_fixed_remaining_legal_kwh",
    "energy_v2_fixed_seconds_remaining",
    "energy_v2_fixed_budget_power_w",
    "energy_v2_fixed_projected_average_w",
    "energy_v2_trailing_remaining_operational_kwh",
    "energy_v2_trailing_remaining_legal_kwh",
    "energy_v2_trailing_budget_power_w",
    "energy_v2_trailing_projected_average_w",
)

LEGACY_MASTER_HELPER_KEYS: tuple[str, ...] = (
    "legacy_enabled",
    "current_energy_trading_enabled",
)

OWNED_ACTUATORS: tuple[str, ...] = (
    "select.solax_charger_use_mode",
    "select.solax_manual_mode_select",
    "number.solax_battery_discharge_max_current",
    "number.solax_battery_charge_max_current",
    "number.solax_remotecontrol_active_power",
    "number.solax_remotecontrol_autorepeat_duration",
    "select.solax_remotecontrol_power_control",
    "button.solax_remotecontrol_trigger",
    "select.deye_work_mode",
    "select.deye_time_of_use",
    "select.deye_ac_coupling",
    "switch.deye_export_surplus",
    "switch.deye_battery_grid_charging",
    "number.deye_grid_max_export_power",
    "number.deye_export_surplus_power",
    "number.deye_grid_max_import_power",
    "number.deye_battery_grid_charging_current",
    "number.deye_battery_max_charging_current",
    "number.deye_battery_max_discharging_current",
)

DEFAULT_CONFLICTING_AUTOMATIONS: tuple[str, ...] = (
    "automation.fve_solax_zpet_do_self_use_po_vybiti_deye",
    "automation.rizeni_solaxu_podle_kalendare_nakup",
    "automation.rizeni_solaxu_podle_kalendare_prodej",
    "automation.deye_rizeni_baterie_dle_ceny_nabijeni_vybijeni",
    "automation.gridcontrol_charge",
    "automation.spust_vybijeno_deye_v_konkretni_cas",
    "automation.vypne_vybijeni_deye_a_zapne_self_use_mod_na_solaxu",
    "automation.zpnout_nabijeni_deye_v_ucity_cas",
)


def parse_charge_shadow_config(
    appdaemon_args: Any,
) -> tuple[ChargeControllerParameters, tuple[str, ...]]:
    """Build a validated, fail-safe charge-shadow model from AppDaemon args."""
    defaults = ChargeControllerParameters()
    if not isinstance(appdaemon_args, dict):
        return defaults, ("AppDaemon args must be a mapping",)
    if "charge_shadow" not in appdaemon_args:
        return defaults, ("missing required charge_shadow mapping",)
    source = appdaemon_args.get("charge_shadow")
    if not isinstance(source, dict):
        return defaults, ("charge_shadow must be a mapping",)
    values: dict[str, object] = {}
    errors: list[str] = []
    for name in ChargeControllerParameters.__dataclass_fields__:
        raw = source.get(name, getattr(defaults, name))
        try:
            values[name] = int(raw) if name == "conflict_attempt_limit" else float(raw)
        except (TypeError, ValueError):
            errors.append(f"invalid charge_shadow.{name}")
            values[name] = getattr(defaults, name)
    parameters = ChargeControllerParameters(**values)  # type: ignore[arg-type]
    errors.extend(f"charge_shadow.{error}" for error in validate_charge_controller_parameters(parameters))
    return parameters, tuple(errors)
